FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine

WORKDIR /src

ENV ASPNETCORE_ENVIRONMENT=Development \
	DOTNET_USE_POLLING_FILE_WATCHER=true \
	NUGET_XMLDOC_MODE=skip

RUN apk add --no-cache nodejs npm && \
	npm install -g pnpm@10 && pnpm config set confirmModulesPurge false

CMD ["dotnet", "run", "--no-launch-profile", "--project", "src/GZCTF/GZCTF.csproj", "--urls", "http://0.0.0.0:8080"]
